### ISSUE TITLE
Solution doesn't follow prompt

### ISSUE THREAD

**Issue by drkfitz13** [learn-co-curriculum/dsc-looping-over-collections-lab#3]
In the solution page, when defining city_indicies, the prompt asks for you to use len(). The solution doesn't use len().

**Comment by Cheffrey2000** [comment]
This issue has been fixed by this commit [42949fc](https://github.com/learn-co-curriculum/dsc-looping-over-collections-lab/commit/42949fc5bc1b549f78adba6856c1ced89eca747e)
