### ISSUE TITLE
Unable to see assignment instructions, only see blank notebook titled "Index"

### ISSUE THREAD

**Issue by ShubSharma123** [learn-co-curriculum/dsc-looping-over-collections-lab#4]
## Link to Canvas

https://learning.flatironschool.com/courses/7380/assignments/258627?module_item_id=613169

## Issue Subtype

[ ] Master branch code
[ ] Solution branch code
[ ] Code tests
[**X**] Layout/rendering issue
[ ] Instructions unclear
[**X**] Other (explain below)

### Source

```
**There is no code or markdown causing the issue, because I cannot even see the assignment instructions. I am able to open Saturn Cloud, but all I see is a completely blank notebook titled "index".**
```

### Concern

**There is no code or markdown causing the issue, because I cannot even see the assignment instructions. I am able to open Saturn Cloud, but all I see is a completely blank notebook titled "Index".**

## (Optional) Proposed Solution

**I do not have a suggestion for alternative code or markdown that would resolve the issue.**

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [**X**] Saturn Cloud from Canvas

## Any Additional Context?

**This is the first time in the course that I have really had an issue with Saturn Cloud from Canvas and if I cannot even see the assignment instructions, then obviously I will not be able to successfully complete it. Please resolve the issue as soon as possible. Thank you so much!**

**Comment by bpurdy-ds** [comment]
Thank you for brining this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
I just clicked on the Saturn Cloud link, and it opened up the way it was supposed to. Very occasionally the link does not open properly "the first time", and you need to close that tab, and click on the link within Canvas again. I'll count this as resolved, but if you are still having issue then please reopen.

**Comment by ShubSharma123** [comment]
Hello, I just closed and re-opened the Saturn Cloud link within Canvas, but it still shows the same thing. The lessons and labs before and after this one opened up the way they were supposed to, but not this one for some reason.

**Comment by bpurdy-ds** [comment]
I'm having a colleague check on her machine. Are you using Chrome? If so, and still having issues. Perhaps clear your cache?

**Comment by bpurdy-ds** [comment]
She got it to work, just said it took a little while to load. Thus, I iterate my suggestions above. Please let me know.

**Comment by ShubSharma123** [comment]
Yes, Chrome. I am not at my computer right now, so I will do what you suggested when I get back to it in a couple of hours.

**Comment by ShubSharma123** [comment]
Clearing my cache did not work.

**Comment by bpurdy-ds** [comment]
If you are able, it may be worth to try this on a different machine.
We can do a work around with [Google colab](https://colab.google/). If you want to try that, I'll send you the two files you'd need to upload into Colab.

**Comment by ShubSharma123** [comment]
Sure, I can give it a try.

**Comment by bpurdy-ds** [comment]
[cities.xlsx](https://github.com/learn-co-curriculum/dsc-looping-over-collections-lab/files/13663931/cities.xlsx)
is the data

**Comment by bpurdy-ds** [comment]
[README.md](https://github.com/learn-co-curriculum/dsc-looping-over-collections-lab/files/13663937/README.md)
GH won't support the python notebook file, so here is the readme. You'll need to drop the data in and then copy and paste this. I made a couple of the instructors aware of your situation and they are going to take over from here. Best.

**Comment by cmhollman** [comment]
Hello, 
I'll be taking over this issue from here. Building off of the Google Collab approach, I did some of the legwork for you and recreated the assignment here:

https://colab.research.google.com/drive/1N-o0aKFXFV2wgwGp1t8c1YE5q0qXiTwh

Feel free to either make a copy or edit this one as much as you like.

You'll still need to upload the cities.xlsx file before it will run properly but other than that it should work for you. If you have any questions feel free to reach out either on this ticker or via a Technical Coaching chat during office hours.

**Comment by ShubSharma123** [comment]
Thank you so much for your help. I really appreciate it and I was able to open the notebook without issues this time around!

**Comment by ShubSharma123** [comment]
Thank you so much for your help. I really appreciate it and was able to open the notebook without issues this time around!

**Comment by cmhollman** [comment]
Glad to hear it! Good luck with the rest of prework and please don't hesitate to contact us if you need anything else.

**Comment by ShubSharma123** [comment]
Will do, thank you again.
