### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by rjlatail** [learn-co-curriculum/dsc-looping-over-collections-lab#5]
## Link to Canvas

https://learning.flatironschool.com/courses/7620/assignments/268916?module_item_id=646890

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

### Source

```
The issue is in the downloaded file, not the notebook
```

### Concern

The notebook includes descriptions of what is in the excel file, but those descriptions are incorrect:
1. The cities are not in order by population.
2. The values for Toronto's area and population are inverted.
3. The values for Buenos Aires and Toronto's population differ than what is described in the notebook.

## (Optional) Proposed Solution

Please fix the data in the excel file to ensure that it is correct.

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
We'll take a look.
Thank you for bringing this to our attention.

**Comment by bpurdy-ds** [comment]
We don't see any of those issues. So I'll close the ticket. Please follow-up with your instructor if you still think something is awry.
