### ISSUE TITLE
Problem with spreadsheet

### ISSUE THREAD

**Issue by cayke-fda** [learn-co-curriculum/dsc-looping-over-collections-lab#6]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)

### Source

```
The spreadsheet used during this segment of the class has some data inverted. The population and area for Toronto are inverted causing the results to be wrong. Not only that but the data is not given to the user organized by rank (highest population), which is something said to be true in the notebook.
```

### Concern

Toronto's population and area are inverted and the cities are not organized by rank.

## (Optional) Proposed Solution

Fix spreadsheet.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ x] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Taking a look. Thank you for flagging this issue.

**Comment by bpurdy-ds** [comment]
As it should be here in the repo, but for some reason not the case with the link within Canvas. Fixed. If you don't see the update right away in Canvas, then I have also included it here. Please reopen if there are any other issues.
[cities.xlsx](https://github.com/learn-co-curriculum/dsc-looping-over-collections-lab/files/15149920/cities.xlsx)
